/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'welcome' at '14/6/17 8:20 PM' with Gradle 2.9
 *
 * @author welcome, @date 14/6/17 8:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
