import org.junit.Test;

import static com.jayway.restassured.RestAssured.given;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'welcome' at '14/6/17 8:20 PM' with Gradle 2.9
 *
 * @author welcome, @date 14/6/17 8:20 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test
    public void makeSureThatGoogleIsUp() {
        System.out.println(given(). param("id", 2).when().get("http://localhost:8080/get").thenReturn().asString());
    }

    
}

